---
trigger:
  branches:
    exclude:
    - main
  # The following is set manually via the ADO UI as it isn't working for a yet unknown reason
  # paths:
  #   include:
  #   - environments/staging
  #   - modules

pr: none

pool: 'CMRC PreProd Pool'

jobs:
  # - template: templates/terragrunt_job.yml
  #   parameters:
  #     environment: staging
  #     module: applications
  #     subscription: "Azure Pipeline: CMRC-Pre-Prod" #service principal
  #     variableGroupName: 'cmrc-infra-vars-staging'

  - template: templates/terragrunt_job.yml
    parameters:
      environment: staging
      module: base
      subscription: "Azure Pipeline: CMRC-Pre-Prod" #service principal
