environment     = "staging"
location        = "UK South"
project_acronym = "cmrc"
vnet_rg         = "RG-Connectivity"
vnet_name       = "VNET-UKS-CaseManagment-PreProd"
aad_sp_name     = "Azure Pipeline: CMRC-PreProd"
asp_linux_sku   = "P0v3"
asp_windows_sku = "P0v4"
